# Generated by Django 5.2.2 on 2026-01-08 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('Frontend Developer', 'Frontend Developer'), ('Backend Developer', 'Backend Developer'), ('QA Engineer', 'QA Engineer'), ('UI/UX Designer', 'UI/UX Designer'), ('DevOps Engineer', 'DevOps Engineer')], max_length=50, null=True),
        ),
    ]
