# Generated by Django 5.2.2 on 2025-12-22 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notification_notif_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notif_type',
            field=models.CharField(choices=[('task_assigned', 'Task Assigned'), ('task_updated', 'Task Updated'), ('task_due', 'Task Due Soon'), ('task_completed', 'Task Completed'), ('admin_task_created', 'Admin Task Created'), ('admin_task_updated', 'Admin Task Updated'), ('manager_task_overdue', 'Manager Task Overdue'), ('admin_task_overdue', 'Admin Task Overdue')], max_length=50),
        ),
    ]
